### ISSUE TITLE
Record to JS object function not added when using a record with type variable

### ISSUE THREAD

**Issue by jchavarri** [cristianoc/genFlow#35]
I have the following:

```rust
[@genFlow]
type basicAction = {
  actionType: string,
  payload: string,
};

[@genFlow]
let createBasicAction = (actionType, payload) => {actionType, payload};
```

which produces:
```js
export type basicAction = {|actionType:string, payload:string|};
export const createBasicAction: (string, string) => basicAction = function _(Arg1, Arg2) { const result = TestBS.createBasicAction(Arg1, Arg2); return {actionType:result[0], payload:result[1]} };
```

Then I tried:

```rust
[@genFlow]
type action('a) = {
  actionType: string,
  payload: 'a,
};

[@genFlow]
let createAction = (actionType, payload) => {actionType, payload};
```

And genFlow outputs:

```js
export type action<a> = {|actionType:string, payload:a|};
export const createAction: <T1>(string, T1) => action<T1> = TestBS.createAction;
```

In the first case, `createBasicAction` wraps the array with a JS object `{actionType:result[0], payload:result[1]}`.
In the last case though, `createAction` –that returns a generic type in Flow– doesn't include the JS object wrapping and directly returns the value from `TestBS.createAction`. I was expecting it to behave like `createBasicAction` and have the returned value wrapped.

I guess this is known, but I couldn't find this particular case in the README. I wanted to make sure I'm not doing anything wrong, is there a way to have the converting code added to functions with this kind of types?

**Comment by cristianoc** [comment]
@jchavarri fix coming.
Notice though that this is walking on thin ice: if the conversion is performed when the type argument is still unknown (i.e. a variable not yet instantiated to a specific type), then the identity conversion is performed. This means that if the payload `'a` is instantiated later on, it won't be converted.

**Comment by jchavarri** [comment]
Thanks @cristianoc ! This works great :)

> Notice though that this is walking on thin ice: if the conversion is performed when the type argument is still unknown (i.e. a variable not yet instantiated to a specific type), then the identity conversion is performed.

I'm not sure I follow. If I understand correctly, this case should perform the identity conversion:

```rust
[@genFlow]
type action('a) = {
  actionType: string,
  payload: 'a,
};

[@genFlow]
let createAction = (actionType, payload) => {actionType, payload};
```

However, I get this (which is pretty awesome btw, not complaining 😄 )

```js
export type action<a> = {|actionType:string, payload:a|};
export const createAction: <T1>(string, T1) => action<T1> = function _(Arg1, Arg2) { const result = TestBS.createAction(Arg1, Arg2); return {actionType:result[0], payload:result[1]} };
```

In that case, the variable (`'a` in Reason, which gets converted to `T1` in Flow) is still "free" / not instantiated, right?

**Comment by cristianoc** [comment]
@jchavarri the issue one can face, which I did not explain very well, is that the conversion for the payload itself is always the identity function.

Consider the following code:
```reason
[@genType]
type payload('a) = {payload: 'a};

[@genType]
let getPayload = ({payload}) => payload;

[@genType]
type record = {v: int};

[@genType]
let getPayloadRecord = ({payload}): record => payload;

[@genType]
let record1 = {v: 1};

[@genType]
let payload1 = {payload: record1};
```

And the client code on the JavaScript side:
```js
const x1 = getPayload(payload1).v;
const x2 = getPayloadRecord(payload1).v;

console.log("x1 is", x1);
console.log("x2 is", x2);
```

This gives:
```
x1 is undefined
x2 is 1
```

Only `getPayloadRecord`, whose type has been instantiated ahead of time, and taken into account in the conversion, gives the right result.

**Comment by jchavarri** [comment]
Oooh I see what you mean now. So one has to be careful when using nested records (actually nested _anything_) and type variables, because the functions working with these types only know the type at the "top". I wonder if this is something that could be added as a comment in the output 🤔 similar to the `// No need to import locally visible type action. Make sure it is also marked with @genType` comments, but at least in my case, I think I would have realized before running into that.

The way I'm modelling this (a migration of some Redux actions/reducers to Reason) is by keeping the payload under a variant type, so the problem you mention wouldn't happen (as the payload type would remain in the Reason domain). I have found an issue with this though, because in very few cases I still need to read the payload from JavaScript, so I did:

```reason
[@genType]
type payload('a) = {payload: 'a};

let wrapAction = action => {payload: action};

[@genFlow]
type actionPayload =
  | DidScroll(int)
  | DidResize(int, int);

let didScroll = a => wrapAction(DidScroll(a));

[@genFlow]
let unwrapDidScrollPayloadForJs = a =>
  switch (a) {
  | DidScroll(a) => Some(a)
  | _ => None
  };
```

This has produced:

```js
export const unwrapDidScrollPayloadForJs: (actionPayload) => ?number = TestBS.unwrapPayloadForJs;
```

which is just _perfect_ ✨ for what I need. 

Thanks a lot for explaining!

**Comment by cristianoc** [comment]
@jchavarri actually I was wrong and my example should have worked.
What was missing was instantiation of type variables before generating the conversion (done in https://github.com/cristianoc/genFlow/commit/9712a60fab3ef0f31ad074f15a4256939f9e40a6).

Turns out that delayed instantiation is not actually a problem.
Here's a somewhat verbose description, to try and work out what's going on in detail.

### So given this function:
```reason
getPayload : payload('a) => 'a
```
the js side sees a function which can be thought of type
```reason
{. payload: 'a} => 'a
```
The conversion only needs to add the step `conversion: {. payload: 'a} => payload('a)` and this does not need to look inside the `'a`, so having no conversion on `'a` is perfectly fine as the Reason function cannot possibly look inside `'a` because of parametricity. In fact the conversion must be the identity function.

### Consider now the function:
```reason
getPayloadRecord : payload(record) => record
```
the js side sees a function which can be thought of type
```reason
{. payload: {. v: number}} => {. v: number}
```
The conversion must be applied in a nested way.

### Let's now supply a value as argument to the functions:
```reason
payloadValue : payload(record)
```
this will be ```{. payload: {. v: number}}``` on the js side.
Both `getPayload` and `getPayloadRecord` will operate correctly on a value of this type. The difference is that `getPayloadRecord` will do one more level of wrapping and unwrapping. This might seem unnecessarily inefficient, however it's not: that's not the only function of that type.

### Consider now another function with the same type as `getPayloadRecord`:
```reason
getPayloadRecordPlusOne : payload(record) => record
```
which takes out the record and increments the value of `v` by 1. The conversion must work for all functions of this type, including `getPayloadRecordPlusOne`, so the extra unwrapping and wrapping is actually necessary.
